# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4b6f2d6b3c20c6b8f011c50167ec1a2a207252dae97837abd6ea54956971040bc14149d51c5d23bc73fbeefdd070c76c04fa16e4c329bc9e87b79a47ef00cb5d

test:
  secret_key_base: 899af8986d3c77af1ffa1eaf22b6ff3d0e1433e8ed18227bbec455d1d0a591d79c743dd347c6054e3fc60333cf5fd6db0d706501789a770f32ab2b1d87defe53

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
